import { Iproduct } from "./iproduct";

export const allProducts:Iproduct[]=[
      {
            id:1,
            title:"T-shirt",
            description:"plalal",
            price:100,
            quantity:2,
            imgSrc:"assets/images/4.jpg"
      },
      {
            id:2,
            title:"Shoes",
            description:"plalal",
            price:80,
            quantity:0,
            imgSrc:"assets/images/5.jpg"
      },
      {
            id:3,
            title:"Shirt",
            description:"plalal",
            price:70,
            quantity:5,
            imgSrc:"assets/images/9.jpg"
      },
      {
            id:4,
            title:"T-shirt",
            description:"plalal",
            price:100,
            quantity:1,
            imgSrc:"assets/images/10.jpg"
      },
      {
            id:5,
            title:"Shoes",
            description:"plalal",
            price:80,
            quantity:4,
            imgSrc:"assets/images/8.jpg"
      },
      {
            id:6,
            title:"Trosers",
            description:"plalal",
            price:110,
            quantity:1,
            imgSrc:"assets/images/6.jpg"
      },
      {
            id:7,
            title:"T-shirt",
            description:"plalal",
            price:100,
            quantity:2,
            imgSrc:"assets/images/10.jpg"
      },
      {
            id:8,
            title:"Shoes",
            description:"plalal",
            price:80,
            quantity:0,
            imgSrc:"assets/images/5.jpg"
      },
      {
            id:9,
            title:"Tie",
            description:"plalal",
            price:70,
            quantity:3,
            imgSrc:"assets/images/7.jpg"
      }
      ,
      {
            id:10,
            title:"T-shirt",
            description:"plalal",
            price:100,
            quantity:2,
            imgSrc:"assets/images/10.jpg"
      },
      {
            id:11,
            title:"Shoes",
            description:"plalal",
            price:80,
            quantity:0,
            imgSrc:"assets/images/5.jpg"
      },
];
